#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
#!!!!!!!! DO NOT EDIT THIS FILE !!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
#
# Please create a file called ~/.my_shell_complements and put your 
# speficic aliases/exports/functions/whatever there. Let's 
# keep this file simple!
#
BASEDIR=$PWD

#
# check for updates
#
DOTSHELLRC_FILE="$HOME/.dotshellrc"
[ -f "$DOTSHELLRC_FILE"  ] && DOTSHELL_LOC=$(cat "$DOTSHELLRC_FILE") || DOTSHELL_LOC="$HOME/.dotshell"
cd $DOTSHELL_LOC

# Store the current commit hash of the local branch
current_commit=$(git rev-parse HEAD)
# Fetch remote changes without merging
git fetch
# Store the commit hash of the remote-tracking branch
remote_commit=$(git rev-parse @{u})
# Compare the local and remote-tracking branch commit hashes
if [ "$current_commit" != "$remote_commit"  ]; then
    echo "Updating script..."
    git pull
    # reloading
    source $HOME/.zshrc
fi
cd $BASEDIR

## Useful variables
OS=`uname`
BIN_FOLDER=$HOME/.local/bin
export PATH="$BIN_FOLDER:$PATH"

# History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh_history

#_comp_options+=(globdots)		# Include hidden files.

# For some themes which cursor is underline, when exit vim the cursor becomes a box. This function
# fix this error
#_fix_cursor() {
#  echo -ne '\e[3 q'
#}
#precmd_functions+=(_fix_cursor)
#
# common stuff and OS-agostic and independent of complex dependencies
source $HOME/.sh_common

# Complements
# You may want to put all your additions into a separate file like
# ~/.my_bash_complements, instead of adding them here directly.
if [ -f $HOME/.my_shell_stuff ]; then
   . $HOME/.my_shell_stuff
fi

# reload
test alias f5 > /dev/null 2>&1 || alias f5='source $HOME/.zshrc'

# load starship
eval "$(starship init zsh)"
